### ISSUE TITLE
Some notes going into the wrong places

### ISSUE THREAD

**Issue by duncangeere** [evmaki/csv-to-midi#1]
I'm having an issue with this (immensely useful) tool, where some notes are going to the wrong place.

For example, if I use [this CSV](https://www.dropbox.com/s/t81zjmtfcb8ton5/decadal.csv?dl=0), I would expect to get out a MIDI sequence that looks roughly like this visualization of the data:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/11523915/174444640-abb7a3f3-c813-49d4-a0b1-ef7e9e37ee99.png">

Instead, I get a MIDI sequence that looks like this:

<img width="945" alt="image" src="https://user-images.githubusercontent.com/11523915/174444744-52fb16a0-9cfe-4993-916a-4a8976d63e13.png">

I'm using these settings:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/11523915/174444657-58ca61d5-5ee7-4b58-b463-a5257abd5efd.png">

I would expect the lowest note to be on C2, and the highest on C5, but it comes out with the lowest on C1 and the highest on F3, then the note that should be the highest sitting down on C2.

Any idea what might be going on here?

**Comment by evmaki** [comment]
hi there! i'm glad you've found this project useful. thanks for providing detailed info about the problem you're having – i admittedly haven't touched this code in a few years, so it will take me a second to dig deeper and figure out exactly what the issue is. 

at first glance, i'm guessing it has something to do with the way the continuous numerical values in the csv are being 1.) offset to the desired starting octave of the tonic and 2.) clamped to discrete note values thereafter. something isn't quite right there. i will try to set aside some time this week to figure it out.

as an aside: very cool to see others working in this (admittedly niche) space. your work with "loud numbers" is inspiring. always eager to chat and collaborate on these types of projects.

**Comment by duncangeere** [comment]
Tremendously useful! It's one of the key sonification resources I recommend to people who don't want to write code. Thanks so much for your work on it (and for the kind words on Loud Numbers 😍).

Yes - it seems like there are some notes that are going awry. [This CSV](https://www.dropbox.com/s/amok61ytto6o8rl/annual.csv?dl=0) yields what might be more useful results. It should look like this:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/11523915/174548346-0dce897a-a553-4bb2-a5bc-9fe0bafab27c.png">

But it comes out like this:

<img width="2005" alt="image" src="https://user-images.githubusercontent.com/11523915/174548565-59f75653-26c4-4f5b-b4ae-1e3ab0c9780f.png">

A bunch of those notes (on D1) are too low - they look like they should be on D2. Then there's a big string at the end that should be higher and more differentiated - it seems like they've been clipped, then moved down somehow.

I'm running OSX and the latest version of Firefox, in case that's useful to know.

Let me know if you need any more details in your troubleshooting, and thanks for being willing to reopen a project that's been dormant for a few years!

**Comment by evmaki** [comment]
yes, that makes sense musically – including the tonic at the upper end will result in more pleasing outputs. it's no trouble at all to include that extra note. i went ahead and made the change and deployed it. thanks for your helpful feedback! hope the tool continues to be of use.

**Comment by duncangeere** [comment]
Thanks so much for doing that Evan! Really appreciate your willingness to put more time into this :)
